# Generated by Django 3.1.5 on 2021-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRoadBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoadBlockName', models.CharField(max_length=50)),
                ('NumberOfPolice', models.IntegerField(default=0)),
                ('Time', models.DateTimeField()),
                ('Supervisor', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('PoliceID', models.CharField(max_length=200)),
                ('RoadBlock', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
