# Generated by Django 3.1.5 on 2021-05-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0002_allroadblocks_assignedpolice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allroadblocks',
            old_name='RoadBlockName',
            new_name='RoadBlockID',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='LicenceNumber',
            new_name='LicenceID',
        ),
    ]
