# Generated by Django 3.1.5 on 2021-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0003_auto_20210525_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpolice',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='', max_length=50),
        ),
    ]
