# Generated by Django 3.1.5 on 2021-05-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0004_auto_20210525_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllRoadBlocks',
            new_name='AllRoadBlock',
        ),
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
