# Generated by Django 3.1.5 on 2021-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0005_auto_20210525_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='InvoiceNumber',
            new_name='InvoiceID',
        ),
        migrations.AlterField(
            model_name='allroadblock',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='', max_length=40),
        ),
    ]
