# Generated by Django 3.1.5 on 2021-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0006_auto_20210525_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='FullName',
            field=models.CharField(max_length=20),
        ),
    ]
